development:
  adapter: mysql2
  database: golfer_development
  pool: 5
  timeout: 5000
  username: root
  password: password
  host: 127.0.0.1

test:
  adapter: mysql2
  database: golfer_test
  pool: 5
  timeout: 5000
  username: root
  password: password
  host: 127.0.0.1
